// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileOutlined from '/Users/nancy/Documents/zhipu/react18测试/antdpro/mypro-demo1/node_modules/_@ant-design_icons@4.8.0@@ant-design/icons/es/icons/SmileOutlined';
import CrownOutlined from '/Users/nancy/Documents/zhipu/react18测试/antdpro/mypro-demo1/node_modules/_@ant-design_icons@4.8.0@@ant-design/icons/es/icons/CrownOutlined';
import TableOutlined from '/Users/nancy/Documents/zhipu/react18测试/antdpro/mypro-demo1/node_modules/_@ant-design_icons@4.8.0@@ant-design/icons/es/icons/TableOutlined';
export default { SmileOutlined, CrownOutlined, TableOutlined };
